# Generated by Django 5.0.6 on 2024-06-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product_image/')),
                ('active', models.BooleanField(default=True)),
                ('single_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.products')),
            ],
        ),
    ]
